### ISSUE TITLE
Automatic slide numbering

### ISSUE THREAD

**Issue by soulcharmer** [soulcharmer/pubquiz_generator#1]
this can work

                    
        <small>
          <span style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 5px; position: absolute; top: 0px; left: 50px;"> round 1 / question 1</span>
        </small>

Also, the numbering should be automatic so that different rounds can have different number of questions.

**Comment by zelial** [comment]
implemented in 5530f0f12e38639550648409b05ede725b0f241e - I've used the provided snippet as is, on both question and answer slides.
