### ISSUE TITLE
Default output option

### ISSUE THREAD

**Issue by soulcharmer** [soulcharmer/pubquiz_generator#7]
Now, the prototype spits everything to stdout

Could we add -o that would behave like this?

* if not specified, stdout it is
* if specified without a parameter create a *.html based on the name of the input file
* if specified with a parameter, use it a output file name 

check existing file names not to overwrite anything

Thanks!

**Comment by zelial** [comment]
The argument parser doesn't support a parameter to both have and don't have a value. So I picked the one with value and implemented:

`./generate  -i input_template.yaml -t output.template -o output_file.html`
which is equivalent to 
`./generate  -i input_template.yaml -t output.template > output_example.html`

The -o/--output is optional, defaulting to stdout as previously.

implemented in 007489edbe2b1518af080d0d803fd54ecfc877e3
