### ISSUE TITLE
Unicode character rendering

### ISSUE THREAD

**Issue by soulcharmer** [soulcharmer/pubquiz_generator#9]
non-ascii characters cannot be rendered by the generator:

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 4: ordinal not in range(128)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 31: ordinal not in range(128)

**Comment by zelial** [comment]
Fixed in e94ac10639eb9106d71d6da5d3650e591e33c185 by switching to python3 which uses unicode strings by default.
